name: ws-rtmp
region: fra
services:
  - dockerfile_path: Dockerfile
    github:
      branch: master
      deploy_on_push: true
      repo: elektronstudio/ws_rtmp
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    name: ws-rtmp
    routes:
      - path: /
